### ISSUE TITLE
Bug in validation of textures?

### ISSUE THREAD

**Issue by clausnagel** [cityjson/cjval#13]
Can you say why the validation of textures with cjval 0.6.0 fails for this dataset: [building.json](https://github.com/cityjson/cjval/files/14058559/building.json)

Some of the surfaces of the building "`GMLID_BUI184698_512_898`" do not receive textures. Hence, `"null"` is used as value for these surfaces in the `"values"` array. And some of these surfaces have inner rings.

Taking a quick look at the validation code, it seems that the number of rings (i.e. nested arrays) is expected to be equal for `"boundaries"` and `"values"`. However, assume a surface has 6 rings but is assigned no texture by using `"null"` in `"values"`, then 6 != 1 and the validation fails. Or would you expect that `"null"` is given 6 times in this example? Then the count would be equal, but imho this would be redundant. Either you assign texture coordinates to all rings or to none, so a single `"null"` should be sufficient. 

I have checked the [spec](https://www.cityjson.org/specs/2.0.0/#geometry-object-having-texture-s) but couldn't find a matching example.

**Comment by hugoledoux** [comment]
It fails because I made a mistake when coding cjval, thanks for reporting this. I'll fix it ASAP and release 0.6.1

Your assumption of how `null` is correct and what was intended.

Actually there is one line about it in the specs with a snippet: https://github.com/cityjson/specs/blob/main/specs/specs.bs#L1351

**Comment by hugoledoux** [comment]
Merged + new version 0.6.1 + https://validator.cityjson.org/ updated to v0.6.1
