### ISSUE TITLE
nice to have: a "processing..." indicator

### ISSUE THREAD

**Issue by josfeenstra** [cityjson/cjval#2]
When processing a large file, It is unclear if the program is actually doing anything, untill the chrome / firefox popup of "this webpage is slowing down your browser". This could be fixed by introducing web workers (offloading the process to a different thread), and by adding a small indication to tell the user that the program is running.

**Comment by hugoledoux** [comment]
I agree, but this is more suitable for https://github.com/cityjson/cjval_wasm
