### ISSUE TITLE
Cannot reference an extraCityObject within the same extension file

### ISSUE THREAD

**Issue by ozgetufan** [cityjson/cjval#3]
I am trying to map this part of Energy ADE to CityJSON where DHWFacilities, ElectricalAppliances and LightingFacilities inherit from Facilities, and they are all extraCityObjects.
![Screenshot 2021-11-23 113319 copy](https://user-images.githubusercontent.com/71127957/143009450-02c6cd5a-07b5-4f82-a537-7a8b2cfd2c9e.png)

To reference Facilities in DHWFacilities object, I tried adding the line below: 

```
"+DHWFacilities": {
      "allOf": [
        { "$ref": "#/extraCityObjects/+Facilities" },
        ...

```
But when I validate it with cjval, I get the error below: 
![image](https://user-images.githubusercontent.com/71127957/143009593-462cc2c1-7aa7-4760-821d-2537af4650ed.png)

**Comment by hugoledoux** [comment]
@ozgetufan I fixed it, I think, in the 'develop' branch only.

Could you please try?

**Comment by ozgetufan** [comment]
Yes, now I can reference extraCityObjects within the same file. Thanks!
