### ISSUE TITLE
parents/children properties cannot be "inherited" from _AbstractCityObject

### ISSUE THREAD

**Issue by ozgetufan** [cityjson/cjval#4]
I am trying to create an extraCityObject as follows:

```
"+UsageZone": {
      "allOf": [
        {
          "$ref": "cityobjects.schema.json#/_AbstractCityObject"
        },
        {
          "properties": {
               ...
           },
          "additionalProperties": false
         }
      ]
}
```
I thought that I did not need to add extra "parents" and "children" properties since these are already defined in _AbstractCityObject, but I guess because I included additionalProperties: false, cjval gives an error when I try to use parents/children properties in my json file. 

Could this be caused by the validator itself?

**Comment by hugoledoux** [comment]
I think it is: if you remove it then it should be fine, right?

And in general with CityJSON we tend to not restrict the properties, if the user wants to add another one then it,s not an issue, but she has to be aware that it might not be read correctly by all parsers. This follows the philosophy of JSON being "schema-less"...

**Comment by hugoledoux** [comment]
@ozgetufan can you confirm, or not, that what I wrote above works?

**Comment by ozgetufan** [comment]
Yes when I remove it then it is fine, I will do this then thanks Hugo!
