### ISSUE TITLE
CityJSON validator issue

### ISSUE THREAD

**Issue by zacharylee1204** [cityjson/cjval#8]
Hi, I am trying to use the validator (cjval: a validator for CityJSON files) to validate my CityJSON models schema. However, it seems like the validator can only support CityJSON v1.0 or v1.1 schema.  

My CityJSON model is converted from the FME. It seems like FME only support CityJSON v1.0.1 schema? 

May I ask is there any solution so that I can use your CityJSON?

Thank you very much.

Zachary

**Comment by hugoledoux** [comment]
the output of FME is v1.0 (the validator picks the latest version from vX.Y, so v1.0.1 is fine)

**Comment by zacharylee1204** [comment]
Hi Hugo, thanks for the answer. However, the problem seems cannot be solved.

1. My CityJSON model is version 1.0.1. When I use cjval, it said

=== CityJSON schemas ===
CityJSON schemas used: vnone (builtin)
  1. CityJSON version "1.0.1" not supported [only "1.0" and "1.1"]

2. I also tried to upgrade the CityJSON to v.1.1. However, it said 

Error: CityJSON version should be only X.Y (eg '1.0') and not X.Y.Z (eg '1.0.1')

Any advise? Thank you.

Zachary

**Comment by hugoledoux** [comment]
As the error message says: the version should be only X.Y, you have put X.Y.Z in your file.

So change the line for this: `"version": "1.0",` and it'll work

**Comment by zacharylee1204** [comment]
Got it. Thank you very much!
